### ISSUE TITLE
Feature idea: Default commands for bare links

### ISSUE THREAD

**Issue by bartokwiat** [cccaaannn/telegram_youtube_downloader#7]
By default, the bot could treat bare links (URLs without any command before them) as if they had a specific command attached. This would make using the bot faster and more convenient.

This functionality could be optional and configured through a settings file.  If enabled, any link received by the bot without a preceding command would be automatically interpreted as having a designated command, like "/v" or "/a".

So to give an example, when you send
> example.com/video.mp4

the bot could interpret it as
> /v example.com/video.mp4

I think it would be a pretty nice addition to overall functionality.

**Comment by cccaaannn** [comment]
Hi, thanks for the feedback. I might add that if I find enough free time.

**Comment by cccaaannn** [comment]
Hi, you can use this feature on new version [4.5](https://github.com/cccaaannn/telegram_youtube_downloader/releases/tag/4.5)

**Comment by asamofal** [comment]
@cccaaannn Thanks! May I ask you to reconfigure the public version of your bot to `default_command: video`, as seems like it's `null` there now (or not updated yet).

_Just as an idea: this preference can be extracted to the user level, so each user can configure it himself._

**Comment by cccaaannn** [comment]
I would like to keep the public version as null, because for example I primarily use it for audio.

User level preferences can be a good feature, but if I add that I want it to be implemented in a good way which will probably require a database and that makes updating an existing bot more complicated for the maintainer.
You might need to run migrations on startup, and can't introduce breaking changes to db between versions. Also it will complicate the simple running process because you at least have to map a directory for the db.

Maybe I return back to this in the future.
